version: '3'

networks:
  app:
    driver: bridge
  nginx-proxy:
    external: true
services:
    app:
        build:
          context: .
          dockerfile: docker/app/Dockerfile
          args:
            - ENV_FILE=.env.dev
        image: ${APP_IMAGE}
        container_name: ads-acc-landing-1-app
        restart: ${DK_RESTART}
        volumes:
          - /srv/ads-acc-landing-1/cache:/usr/src/app/.next/cache
        logging:
          driver: 'json-file'
          options:
            max-file: '5'
            max-size: '100m'
        networks:
          - app
    nginx:
        build:
          context: .
          dockerfile: docker/nginx/Dockerfile
          args:
            - APP_IMAGE=${APP_IMAGE}
        image: ${NGINX_IMAGE}
        container_name: ads-acc-landing-1-nginx
        logging:
          driver: 'json-file'
          options:
            max-file: '5'
            max-size: '100m'
        restart: ${DK_RESTART}
        ports:
          - "80:80"
        networks:
          - app
          - nginx-proxy
        depends_on:
          - app
